### ISSUE TITLE
Working command for fflive webcam input on Windows, need help with performance

### ISSUE THREAD

**Issue by tom-leamon** [ramiropolla/ffglitch-scripts#1]
I was able to get fflive webcam input working on Windows

`./ffgac -video_size 1920x1080 -f dshow -i "video=HD Pro Webcam C920" -vcodec mpeg4 -mpv_flags +nopimb+forcemv -q 1 -fcode 1 -g max -f rawvideo -flush_packets 1 -y - | ./fflive -probesize 32 -i - -s ./free-for-all/offset.js`

However, the performance is very poor at that resolution. It runs much better at 640x360. Any ideas to maximize the performance of HD resolutions?

**Comment by ramiropolla** [comment]
Maybe the webcam is inputting raw video data, and that's too slow. On Linux that is an issue at least, which I fix by setting `-vcodec mjpeg` before the input. Perhaps you can do the same with dshow. Check the `list_devices` and `list_options` options and see if they let you select a codec.

**Comment by tom-leamon** [comment]
Yes, that did it!

`./ffgac -threads 4 -video_size 1920x1080 -f dshow -vcodec mjpeg -i "video=HD Pro Webcam C920" -vcodec mpeg4 -mpv_flags +nopimb+forcemv -q 1 -fcode 1 -g max -f rawvideo -flush_packets 1 -y - | ./fflive -probesize 32 -i - -s ./free-for-all/offset.js`
